# 1)Write a R program for different types of data structures in R.

# Vector

```python
# Creating a numeric vector
numeric_vector <- c(1, 2, 3, 4, 5)
numeric_vector

# Creating a character vector
character_vector <- c("apple", "banana", "cherry")
character_vector

# Creating a logical vector
logical_vector <- c(TRUE, FALSE, TRUE)
logical_vector

output:
[1] 1 2 3 4 5
[1] "apple"  "banana" "cherry"
[1]  TRUE FALSE  TRUE
```

# Matrices:

```python
# Creating a numeric matrix
numeric_matrix <- matrix(1:6, nrow = 2, ncol = 3)
numeric_matrix

# Creating a character matrix
character_matrix <- matrix(c("A", "B", "C", "D", "E", "F"), nrow = 2, ncol = 3)
character_matrix

output:
[,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

     [,1] [,2] [,3]
[1,] "A"  "C"  "E" 
[2,] "B"  "D"  "F" 
```

# Lists

```python
# Creating a list
my_list <- list(name = c("John","Daniel","Jack"), age = c(30,53,40) ,hobbies = c("reading", "golf","Gaming"))

# Accessing elements in a list
print(my_list)  

output

$name
[1] "John"   "Daniel" "Jack"  

$age
[1] 30 53 40

$hobbies
[1] "reading" "golf"    "Gaming" 
```

# DataFrame:

```python
# Creating a data frame
data_frame <- data.frame(
  Name = c("Alice", "Bob", "Charlie"),
  Age = c(25, 30, 22),
  Gender = c("Female", "Male", "Male")
)

# Accessing elements in a data frame
print(data_frame$Name)  # Accessing the 'Name' column
print(data_frame$Age)  # Accessing the 'Name' column
print(data_frame$Gender)  # Accessing the 'Name' column

output:
[1] "Alice"   "Bob"     "Charlie"
[1] 25 30 22
[1] "Female" "Male"   "Male"  
```

# Factors:

```python
# Creating a factor
gender <- c("Male", "Female", "Male", "Female", "Male")
factor_gender <- factor(gender, levels = c("Male", "Female"))

# Checking levels of a factor
print(factor_gender)

output:
[1] Male   Female Male   Female Male  
Levels: Male Female
```

# Array:

```python
#Creating  an Array
arr <- array(1:24,dim = c(4,3,2))
arr

output:
, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24
```